---
- hosts: kp_env
  vars_files:
   - "{{inventory_dir}}/group_vars/all.yml"
   - "{{inventory_dir}}/common.yml"
  become: yes
  roles:
   - ansible-auto-start-kp-services
   
- hosts: dp_env
  vars_files:
   - "{{inventory_dir}}/group_vars/all.yml"
   - "{{inventory_dir}}/common.yml"
  become: yes
  roles:
   - ansible-auto-start-dp-services
   
- hosts: db_env
  serial: 1
  vars_files:
   - "{{inventory_dir}}/group_vars/all.yml"
   - "{{inventory_dir}}/common.yml"
  become: yes
  roles:
   - ansible-auto-start-db-services
   
