---
- name: stop the logstash service
  service: name=logstash state=stopped
- name: stop the elasticsearch.service service
  service: name=cs-node-1_elasticsearch.service state=stopped
- name: stop the mongod service
  service: name=mongod state=stopped
- name: stop the postgresql service
  service: name=postgresql state=stopped
- name: stop the cassandra service
  service: name=cassandra state=stopped
- name: Check if neo4j is running
  become_user: "{{neo4j_user}}"
  shell: ps -ef | grep "{{neo4j_home}}" | grep -v grep | wc -l
  register: neo4j_process
- name: stop neo4j
  become: yes
  shell:  bin/neo4j stop
  args:
    chdir: "{{neo4j_home}}"
  when: "neo4j_process.stdout == '1'"

